// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huhbctjiuqvbqixmllyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1aGJjdGppdXF2YnFpeG1sbHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTIzMTIsImV4cCI6MjA2NTM4ODMxMn0.1FWw4ARsJEZGR-X16mjYSpPzHJSYD_VFhIKEaxheO4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);